import pyttsx3

engine = pyttsx3.init()
engine.say("""Hello Parth Joshi, hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           hello
           """)
engine.runAndWait()
